### ISSUE TITLE
PF_PACKET not available on OS X

### ISSUE THREAD

**Issue by andypiper** [philsmd/vap11g#3]
Trying to get this to work on the Mac. So far I had to manually install dpkt (and I had to do the same on Linux, so that should probably be listed as a prereq). The script is unable to import PF_PACKET on OS X as that doesn't exist (see http://stackoverflow.com/questions/3792407/python-socket-pf-packet). Would it be possible to use an alternative more cross-platform approach?

**Comment by philsmd** [comment]
Commit https://github.com/philsmd/vap11g/commit/3474111a17985e74d752b9c205e1c28bf8736b47 should add support for MAC OSX (and maybe other non-Linux operating systems).

I've tested this a little bit on a Mac Mini and it works here without any noticable difference from other operating systems (Linux etc)

Could please somebody else (mknet ?, andypiper ?) test with her/his setup too?
Thx
